/* CodeAlpha Object Detection & Tracking — laptop dashboard controller. */
const API_BASE = window.location.port === '5000' ? window.location.origin : (window.location.hostname ? `http://${window.location.hostname}:5000` : 'http://localhost:5000');
const state={serverConnected:false,phoneConnected:false,detectionActive:false,viewMode:'processed',isRecording:false,selectedClasses:['all'],apiRttMs:null,stats:{},detections:[]};
const el={};
function $(id){return document.getElementById(id)}
function cacheElements(){['phoneStatusBadge','phoneStatusText','serverStatusBadge','serverStatusText','detectionStatusBadge','detectionStatusText','apkUrlCode','waitingUrlCode','copyUrlBtn','laptopIpText','clientIpText','lastFrameTimeText','metricFps','metricLatency','metricResolution','metricFrameCount','metricActiveTracks','metricTotalUniqueIds','videoContainer','waitingPlaceholder','processedViewWrap','rawViewWrap','processedFrameImg','rawFrameImg','overlayTrackerName','overlayFps','streamStatusIndicator','streamStatusText','recordingStatusText','inferenceTimeBadge','tabProcessed','tabSplit','tabRaw','startDetectionBtn','stopDetectionBtn','clearResultsBtn','modelSelect','trackerSelect','confRange','confValue','iouRange','iouValue','toggleTrails','toggleHud','classFilterSummary','applySettingsBtn','trackCountBadge','tracksTableBody','refreshTracksBtn','exportScreenshotBtn','quickScreenshotBtn','toggleRecordBtn','quickRecordBtn','toggleRecordText','exportAlert','exportAlertMsg','fullscreenBtn','logToggleHeader','logToggleIcon','logBody','logEntries','toastContainer','metricFpsIndicator','metricLatencyIndicator'].forEach(id=>el[id]=$(id))}
function init(){cacheElements();bindEvents();setupClassChips();addLog(`Dashboard loaded. Backend target: ${API_BASE}`,'info');fetchStatus();fetchSettings();state.pollTimer=setInterval(fetchStatus,1000);state.framePollTimer=setInterval(updateFramesAndDetections,150)}
function bindEvents(){el.confRange.addEventListener('input',e=>el.confValue.textContent=Number(e.target.value).toFixed(2));el.iouRange.addEventListener('input',e=>el.iouValue.textContent=Number(e.target.value).toFixed(2));el.applySettingsBtn.addEventListener('click',applySettings);el.startDetectionBtn.addEventListener('click',startDetection);el.stopDetectionBtn.addEventListener('click',stopDetection);el.clearResultsBtn.addEventListener('click',clearResults);el.copyUrlBtn.addEventListener('click',copyApkUrl);el.tabProcessed.addEventListener('click',()=>setViewMode('processed'));el.tabSplit.addEventListener('click',()=>setViewMode('split'));el.tabRaw.addEventListener('click',()=>setViewMode('raw'));el.exportScreenshotBtn.addEventListener('click',captureScreenshot);el.quickScreenshotBtn.addEventListener('click',captureScreenshot);el.toggleRecordBtn.addEventListener('click',toggleRecording);el.quickRecordBtn.addEventListener('click',toggleRecording);el.fullscreenBtn.addEventListener('click',toggleFullscreen);el.refreshTracksBtn.addEventListener('click',fetchDetections);el.logToggleHeader.addEventListener('click',()=>{el.logBody.classList.toggle('collapsed');el.logToggleIcon.textContent=el.logBody.classList.contains('collapsed')?'▸':'▾'});window.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea'))return;if(e.key.toLowerCase()==='s')captureScreenshot();if(e.key.toLowerCase()==='t'){el.toggleTrails.checked=!el.toggleTrails.checked;applySettings()}if(e.key.toLowerCase()==='h'){el.toggleHud.checked=!el.toggleHud.checked;applySettings()}})}
function setupClassChips(){document.querySelectorAll('.class-chip').forEach(chip=>chip.addEventListener('click',()=>{const cls=chip.dataset.class,all=document.querySelector('.class-chip[data-class="all"]');if(cls==='all'){document.querySelectorAll('.class-chip').forEach(c=>c.classList.remove('active'));all.classList.add('active');state.selectedClasses=['all']}else{all.classList.remove('active');chip.classList.toggle('active');const active=[...document.querySelectorAll('.class-chip.active')].map(c=>c.dataset.class).filter(c=>c!=='all');state.selectedClasses=active.length?active.map(Number):['all'];if(!active.length)all.classList.add('active')}el.classFilterSummary.textContent=state.selectedClasses.includes('all')?'All 80 classes':`${state.selectedClasses.length} selected`}))}
async function fetchJson(path,options={}){const started=performance.now(),response=await fetch(`${API_BASE}${path}`,{cache:'no-store',...options});state.apiRttMs=Math.round(performance.now()-started);if(!response.ok){let message=`HTTP ${response.status}`;try{const body=await response.json();message=body.message||message}catch(_){}throw new Error(message)}return response.json()}
async function fetchStatus(){try{const data=await fetchJson('/status');state.stats=data;state.serverConnected=true;updateServerBadge('connected','Backend Running');const url=data.apk_url||API_BASE;el.apkUrlCode.textContent=url;el.waitingUrlCode.textContent=url;el.laptopIpText.textContent=(data.laptop_ips||[]).join(', ')||'Unavailable';el.clientIpText.textContent=data.client_address&&data.client_address!=='None'?data.client_address:'None';state.phoneConnected=Boolean(data.is_receiving);if(state.phoneConnected){updatePhoneBadge('connected',`Streaming (${data.client_address||'Phone'})`);el.streamStatusIndicator.className='indicator-dot dot-emerald';el.streamStatusText.textContent=`Receiving Android frames from ${data.client_address}`;el.waitingPlaceholder.classList.add('hidden')}else if(data.frame_count>0){updatePhoneBadge('disconnected','Phone Paused');el.streamStatusIndicator.className='indicator-dot dot-amber';el.streamStatusText.textContent=`Phone stream inactive (${data.seconds_since_last_frame}s since last frame)`}else{updatePhoneBadge('waiting','Waiting for Phone');el.streamStatusIndicator.className='indicator-dot dot-amber';el.streamStatusText.textContent='Waiting for Android camera frames...';el.waitingPlaceholder.classList.remove('hidden')}el.metricFps.textContent=Number(data.current_fps||0).toFixed(1);el.overlayFps.textContent=`${Number(data.current_fps||0).toFixed(1)} FPS`;el.metricResolution.textContent=data.resolution||'-- x --';el.metricFrameCount.textContent=Number(data.frame_count||0).toLocaleString();el.metricLatency.textContent=state.apiRttMs==null?'--':state.apiRttMs;el.metricLatencyIndicator.textContent=state.apiRttMs==null?'● API round-trip':`● API round-trip (${state.apiRttMs}ms)`;el.lastFrameTimeText.textContent=data.seconds_since_last_frame==null?'No frames yet':`${data.seconds_since_last_frame}s ago`;el.inferenceTimeBadge.textContent=`Inference: ${Number(data.inference_time_ms||0).toFixed(1)}ms`;el.detectionStatusBadge.className=`status-pill ${data.detection_active?'active':'disconnected'}`;el.detectionStatusText.textContent=data.detection_active?'Detection Active':'Detection Stopped';state.detectionActive=Boolean(data.detection_active);setRecordingState(Boolean(data.recording));if(data.engine_error)addLog(`[ENGINE] ${data.engine_error}`,'error')}catch(err){state.serverConnected=false;state.phoneConnected=false;updateServerBadge('error','Server Offline');updatePhoneBadge('disconnected','Disconnected');el.streamStatusIndicator.className='indicator-dot dot-rose';el.streamStatusText.textContent=`Backend unavailable: ${err.message}`}}
let frameBusy=false;async function updateFramesAndDetections(){if(!state.serverConnected||!state.phoneConnected||frameBusy)return;frameBusy=true;try{const stamp=Date.now();if(state.viewMode==='processed'||state.viewMode==='split')el.processedFrameImg.src=`${API_BASE}/processed_frame?t=${stamp}`;if(state.viewMode==='raw'||state.viewMode==='split')el.rawFrameImg.src=`${API_BASE}/latest_frame?t=${stamp}`;await fetchDetections()}catch(err){addLog(`[STREAM] ${err.message}`,'error')}finally{frameBusy=false}}
async function fetchDetections(){try{const data=await fetchJson('/detections');state.detections=data.active_tracks||[];el.metricActiveTracks.textContent=data.active_count||0;el.metricTotalUniqueIds.textContent=data.total_unique_tracks||0;el.trackCountBadge.textContent=`${data.active_count||0} Active`;el.inferenceTimeBadge.textContent=`Inference: ${Number(data.inference_time_ms||0).toFixed(1)}ms`;renderTracksTable(state.detections);if(data.error&&state.detectionActive)addLog(`[DETECTION] ${data.error}`,'error')}catch(err){addLog(`[DETECTIONS] ${err.message}`,'error')}}
function setViewMode(mode){state.viewMode=mode;[el.tabProcessed,el.tabSplit,el.tabRaw].forEach(b=>b.classList.remove('active'));({processed:el.tabProcessed,split:el.tabSplit,raw:el.tabRaw}[mode]).classList.add('active');el.videoContainer.className=`video-container mode-${mode}`;el.processedViewWrap.className=`frame-wrap ${mode==='raw'?'hidden':'active'}`;el.rawViewWrap.className=`frame-wrap ${mode==='processed'?'hidden':'active'}`}
function renderTracksTable(tracks){if(!tracks.length){el.tracksTableBody.innerHTML='<tr class="empty-row"><td colspan="5">No active objects tracked in the current frame</td></tr>';return}el.tracksTableBody.innerHTML=tracks.map(o=>`<tr><td><span class="id-badge">#${o.track_id??'?'}</span></td><td><strong>${escapeHtml(o.class_name)}</strong></td><td><span class="conf-pill">${(Number(o.conf)*100).toFixed(0)}%</span></td><td><code>${o.centroid?`(${o.centroid[0]}, ${o.centroid[1]})`:'--'}</code></td><td>${escapeHtml(o.last_seen_time||'live')}</td></tr>`).join('')}
async function startDetection(){try{await fetchJson('/start-detection',{method:'POST'});showToast('Detection started','success');addLog('[DETECTION] Started.','success');fetchStatus()}catch(e){showToast(`Start failed: ${e.message}`,'error');addLog(`[ERROR] ${e.message}`,'error')}}
async function stopDetection(){try{await fetchJson('/stop-detection',{method:'POST'});showToast('Detection stopped','info');addLog('[DETECTION] Stopped.','info');fetchStatus()}catch(e){showToast(`Stop failed: ${e.message}`,'error')}}
async function clearResults(){try{await fetchJson('/clear-results',{method:'POST'});showToast('Tracking results reset','info');fetchDetections()}catch(e){showToast(`Reset failed: ${e.message}`,'error')}}
async function fetchSettings(){try{const s=await fetchJson('/settings');el.modelSelect.value=s.model||'yolo11n.pt';el.trackerSelect.value=s.tracker||'bytetrack.yaml';el.confRange.value=s.conf??.35;el.confValue.textContent=Number(s.conf??.35).toFixed(2);el.iouRange.value=s.iou??.45;el.iouValue.textContent=Number(s.iou??.45).toFixed(2);el.toggleTrails.checked=s.show_trails!==false;el.toggleHud.checked=s.show_hud!==false;el.overlayTrackerName.textContent=(s.tracker||'').includes('botsort')?'BoT-SORT':'ByteTrack'}catch(e){addLog(`[SETTINGS] ${e.message}`,'error')}}
async function applySettings(){const payload={model:el.modelSelect.value,tracker:el.trackerSelect.value,conf:Number(el.confRange.value),iou:Number(el.iouRange.value),classes:state.selectedClasses.includes('all')?null:state.selectedClasses,show_trails:el.toggleTrails.checked,show_hud:el.toggleHud.checked};try{await fetchJson('/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});el.overlayTrackerName.textContent=payload.tracker.includes('botsort')?'BoT-SORT':'ByteTrack';showToast('Settings applied','success');addLog(`[SETTINGS] ${payload.model}, ${payload.tracker}, conf=${payload.conf}, IoU=${payload.iou}`,'info')}catch(e){showToast(`Settings error: ${e.message}`,'error');addLog(`[SETTINGS] ${e.message}`,'error')}}
async function captureScreenshot(){try{const data=await fetchJson('/screenshot',{method:'POST'});if(data.status!=='ok')throw new Error(data.message||'Capture failed');showToast('Screenshot captured','success');const a=document.createElement('a');a.href=`${API_BASE}${data.url}`;a.download=data.file.split(/[\\/]/).pop();document.body.appendChild(a);a.click();a.remove()}catch(e){showToast(`Screenshot failed: ${e.message}`,'error')}}
async function toggleRecording(){const action=state.isRecording?'stop':'start';try{const data=await fetchJson(`/recording/${action}`,{method:'POST'});if(data.status!=='ok')throw new Error(data.message||'Recording failed');setRecordingState(action==='start');showToast(action==='start'?'Recording started':'Recording stopped','success')}catch(e){showToast(`Recording error: ${e.message}`,'error')}}
function setRecordingState(active){state.isRecording=active;el.toggleRecordText.textContent=active?'Stop Recording':'Start Recording Video';el.recordingStatusText.classList.toggle('hidden',!active);el.quickRecordBtn.classList.toggle('recording',active)}
function toggleFullscreen(){if(!document.fullscreenElement)el.videoContainer.requestFullscreen().catch(e=>showToast(`Fullscreen error: ${e.message}`,'error'));else document.exitFullscreen()}
function updateServerBadge(status,label){el.serverStatusBadge.className=`status-pill ${status}`;el.serverStatusText.textContent=label}
function updatePhoneBadge(status,label){el.phoneStatusBadge.className=`status-pill ${status}`;el.phoneStatusText.textContent=label}
function copyApkUrl(){const url=el.apkUrlCode.textContent;if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(url).then(()=>showToast('APK URL copied','success')).catch(()=>fallbackCopy(url))}else{fallbackCopy(url)}}
function fallbackCopy(url){const input=document.createElement('textarea');input.value=url;input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();try{document.execCommand('copy');showToast('APK URL copied','success')}catch(_){showToast(`Copy manually: ${url}`,'info')}input.remove()}
function showToast(msg,type='info'){const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=msg;el.toastContainer.appendChild(t);setTimeout(()=>t.remove(),4000)}
function addLog(message,type='info'){if(!el.logEntries)return;const line=document.createElement('div');line.className=`log-line ${type}`;line.textContent=`[${new Date().toLocaleTimeString()}] ${message}`;el.logEntries.appendChild(line);el.logEntries.scrollTop=el.logEntries.scrollHeight}
function escapeHtml(value){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
document.addEventListener('DOMContentLoaded',init);
